services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=notify
      - DB_PASSWORD=notify_pass
      - DB_NAME=notifications
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_ADDR=redis:6379
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: notify
      POSTGRES_PASSWORD: notify_pass
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notify -d notifications"]
      interval: 5s
      timeout: 3s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  k6:
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
    environment:
      - BASE_URL=http://app:8080
    depends_on:
      app:
        condition: service_started
    profiles:
      - test
volumes:
  pgdata:                                